version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/lib/p2p"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[chore](p2p)"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/lib/relay"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[chore](relay-lib)"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/lib/relay/.config/docker"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[chore](relay-lib)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[chore]"
    groups:
      actions:
        patterns:
          - "*"
